[server]
headless = true
maxUploadSize = 50

[browser]
gatherUsageStats = false

[theme]
primaryColor = "#2ecc71"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#262730"
